const STAGES=['Não iniciado','Dia 1','Dia 2','Dia 3','Dia 4','Conectado','Ganho','Perdido'];
const DEFAULT_ORIGINS=['Perdidos Closer','Perdidos Conectados SDR','Dia 7','Self','Indicação','Outra'];
let db=null,user=null,leads=[],csvRows=[],csvHeaders=[];
const $=id=>document.getElementById(id); const show=(id,on=true)=>$(id).classList.toggle('hidden',!on);
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500)}
function config(){return {url:localStorage.getItem('rw_supabase_url')||'',key:localStorage.getItem('rw_supabase_key')||''}}
function initClient(){const c=config();if(!c.url||!c.key)return false;db=window.supabase.createClient(c.url,c.key);return true}
async function start(){if(!initClient()){show('setupView');return} const {data}=await db.auth.getSession();if(data.session){user=data.session.user;openApp()}else show('loginView');}
$('saveSetup').onclick=()=>{localStorage.setItem('rw_supabase_url',$('setupUrl').value.trim());localStorage.setItem('rw_supabase_key',$('setupKey').value.trim());location.reload()};
$('changeSetup').onclick=()=>{show('loginView',false);show('setupView');const c=config();$('setupUrl').value=c.url;$('setupKey').value=c.key};
$('loginForm').onsubmit=async e=>{e.preventDefault();const {data,error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error)return toast(error.message);user=data.user;openApp()};
$('logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};
async function openApp(){show('setupView',false);show('loginView',false);show('appView');$('userEmail').textContent=user.email;fillStaticOptions();await loadLeads();}
function fillStaticOptions(){$('stage').innerHTML=STAGES.map(x=>`<option>${x}</option>`).join('');$('originOptions').innerHTML=DEFAULT_ORIGINS.map(x=>`<option value="${x}">`).join('');}
async function loadLeads(){const {data,error}=await db.from('leads').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);leads=data||[];renderFilters();renderBoard();}
function renderFilters(){const values=[...new Set([...DEFAULT_ORIGINS,...leads.map(x=>x.origem).filter(Boolean)])];const keep=$('originFilter').value;$('originFilter').innerHTML='<option value="">Todas as origens</option>'+values.map(x=>`<option>${escapeHtml(x)}</option>`).join('');$('originFilter').value=keep;}
function filtered(){const q=$('searchInput').value.toLowerCase(),o=$('originFilter').value;return leads.filter(x=>(!q||x.clinica.toLowerCase().includes(q))&&(!o||x.origem===o));}
function renderBoard(){const list=filtered();$('leadCount').textContent=`${list.length} lead(s)`;$('board').innerHTML=STAGES.map(stage=>{const items=list.filter(x=>x.etapa===stage);return `<section class="column"><div class="column-head"><span>${stage}</span><span class="badge">${items.length}</span></div><div class="dropzone" data-stage="${stage}">${items.map(card).join('')}</div></section>`}).join('');document.querySelectorAll('.lead-card').forEach(el=>{el.onclick=()=>editLead(el.dataset.id);el.ondragstart=()=>el.classList.add('dragging');el.ondragend=()=>el.classList.remove('dragging')});document.querySelectorAll('.dropzone').forEach(z=>{z.ondragover=e=>e.preventDefault();z.ondrop=async e=>{e.preventDefault();const el=document.querySelector('.dragging');if(el)await moveLead(el.dataset.id,z.dataset.stage)}})}
function card(x){return `<article class="lead-card" draggable="true" data-id="${x.id}"><h3>${escapeHtml(x.clinica)}</h3><div class="meta"><span>${escapeHtml(x.origem||'Sem origem')}</span><span>Última atividade: ${fmtDate(x.ultima_atividade)}</span>${Number(x.valor_recuperado)>0?`<span class="value">${money(x.valor_recuperado)}</span>`:''}</div></article>`}
async function moveLead(id,etapa){const patch={etapa};if(['Dia 1','Dia 2','Dia 3','Dia 4','Conectado','Ganho','Perdido'].includes(etapa))patch.trabalhado_em=new Date().toISOString().slice(0,10);if(etapa==='Conectado')patch.conectado=true;const {error}=await db.from('leads').update(patch).eq('id',id);if(error)return toast(error.message);await loadLeads()}
$('searchInput').oninput=renderBoard;$('originFilter').onchange=renderBoard;$('clearFilters').onclick=()=>{$('searchInput').value='';$('originFilter').value='';renderBoard()};
$('newLeadBtn').onclick=()=>openLead(); document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function openLead(x=null){$('leadForm').reset();$('leadId').value=x?.id||'';$('dialogTitle').textContent=x?'Editar lead':'Novo lead';$('clinicName').value=x?.clinica||'';$('origin').value=x?.origem||'';$('stage').value=x?.etapa||'Não iniciado';$('crmUrl').value=x?.link_crm||'';$('result').value=x?.resultado||'';$('recoveredValue').value=x?.valor_recuperado||'';$('lastActivity').value=x?.ultima_atividade||'';$('notes').value=x?.observacoes||'';show('deleteLead',!!x);show('actionsSection',!!x);show('openCrm',!!x?.link_crm);if(x?.link_crm)$('openCrm').href=x.link_crm;$('leadDialog').showModal();if(x)loadActions(x.id)}
function editLead(id){openLead(leads.find(x=>x.id===id))}
$('leadForm').onsubmit=async e=>{e.preventDefault();const id=$('leadId').value;const row={clinica:$('clinicName').value.trim(),origem:$('origin').value.trim(),etapa:$('stage').value,link_crm:$('crmUrl').value.trim()||null,resultado:$('result').value.trim()||null,valor_recuperado:Number($('recoveredValue').value||0),ultima_atividade:$('lastActivity').value||null,observacoes:$('notes').value.trim()||null,user_id:user.id};if(row.etapa!=='Não iniciado')row.trabalhado_em=row.ultima_atividade||new Date().toISOString().slice(0,10);if(row.etapa==='Conectado')row.conectado=true;const res=id?await db.from('leads').update(row).eq('id',id):await db.from('leads').insert(row);if(res.error)return toast(res.error.message);$('leadDialog').close();await loadLeads();toast('Lead salvo')};
$('deleteLead').onclick=async()=>{if(!confirm('Excluir este lead e seus registros?'))return;const {error}=await db.from('leads').delete().eq('id',$('leadId').value);if(error)return toast(error.message);$('leadDialog').close();await loadLeads()};
async function loadActions(leadId){const {data,error}=await db.from('acoes').select('*').eq('lead_id',leadId).order('data_acao',{ascending:false});if(error)return toast(error.message);$('actionsList').innerHTML=(data||[]).map(a=>`<details class="action-item"><summary>${escapeHtml(a.tipo)} · ${fmtDate(a.data_acao)}</summary><p>${escapeHtml(a.descricao)}</p></details>`).join('')||'<p class="muted">Nenhum registro rápido.</p>'}
$('actionForm').onsubmit=async e=>{e.preventDefault();const leadId=$('leadId').value;const date=$('actionDate').value;const {error}=await db.from('acoes').insert({lead_id:leadId,user_id:user.id,data_acao:date,tipo:$('actionType').value,descricao:$('actionDescription').value.trim()});if(error)return toast(error.message);await db.from('leads').update({ultima_atividade:date,trabalhado_em:date}).eq('id',leadId);$('actionDescription').value='';await loadActions(leadId);await loadLeads();toast('Ação registrada')};
$('importBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>{const f=e.target.files[0];if(!f)return;Papa.parse(f,{header:true,skipEmptyLines:true,complete:r=>{csvRows=r.data;csvHeaders=r.meta.fields||[];buildMapping();$('importDialog').showModal()}})};
function buildMapping(){const fields=[['clinica','Clínica / lead'],['origem','Origem'],['link_crm','Link HubSpot'],['resultado','Resultado'],['valor_recuperado','Valor recuperado'],['ultima_atividade','Última atividade']];$('mapping').innerHTML=fields.map(([k,l])=>`<div class="mapping-row"><strong>${l}</strong><select data-map="${k}"><option value="">Não importar</option>${csvHeaders.map(h=>`<option ${guess(k,h)?'selected':''}>${escapeHtml(h)}</option>`).join('')}</select></div>`).join('')}
function guess(k,h){h=h.toLowerCase();return (k==='clinica'&&/(cl[ií]nica|lead|nome)/.test(h))||(k==='origem'&&/origem/.test(h))||(k==='link_crm'&&/(link|hubspot|url)/.test(h))||(k==='resultado'&&/resultado/.test(h))||(k==='valor_recuperado'&&/valor/.test(h))||(k==='ultima_atividade'&&/(atividade|data)/.test(h))}
$('confirmImport').onclick=async()=>{const map={};document.querySelectorAll('[data-map]').forEach(s=>map[s.dataset.map]=s.value);if(!map.clinica)return toast('Selecione a coluna da clínica/lead');const rows=csvRows.map(r=>({user_id:user.id,clinica:String(r[map.clinica]||'').trim(),origem:String(r[map.origem]||'Outra').trim()||'Outra',link_crm:map.link_crm?String(r[map.link_crm]||'').trim()||null:null,resultado:map.resultado?String(r[map.resultado]||'').trim()||null:null,valor_recuperado:map.valor_recuperado?parseMoney(r[map.valor_recuperado]):0,ultima_atividade:map.ultima_atividade?parseDate(r[map.ultima_atividade]):null,etapa:'Não iniciado'})).filter(x=>x.clinica);const {error}=await db.from('leads').insert(rows);if(error)return toast(error.message);$('importDialog').close();$('fileInput').value='';await loadLeads();toast(`${rows.length} lead(s) importado(s)`)};
$('reportBtn').onclick=()=>{$('reportDialog').showModal()};$('generateReport').onclick=()=>{const s=$('reportStart').value,e=$('reportEnd').value;const rows=leads.filter(x=>(!s||x.ultima_atividade>=s)&&(!e||x.ultima_atividade<=e)&&x.etapa!=='Não iniciado');const summary={worked:rows.length,connected:rows.filter(x=>x.conectado||['Conectado','Ganho'].includes(x.etapa)).length,won:rows.filter(x=>x.etapa==='Ganho').length,lost:rows.filter(x=>x.etapa==='Perdido').length,value:rows.reduce((a,x)=>a+Number(x.valor_recuperado||0),0)};const w=open('','_blank');w.document.write(reportHtml(rows,summary,s,e));w.document.close()};
function reportHtml(rows,s,a,b){return `<!doctype html><html><head><meta charset="utf-8"><title>Relatório Recovery Workspace</title><style>@page{size:A4 landscape;margin:12mm}body{font:12px Arial;color:#222}h1{margin:0 0 4px}.summary{display:flex;gap:12px;margin:18px 0}.k{border:1px solid #ccc;border-radius:8px;padding:10px;min-width:120px}.k b{display:block;font-size:18px;margin-top:4px}table{width:100%;border-collapse:collapse}th,td{padding:7px;border:1px solid #ccc;text-align:left;vertical-align:top}th{background:#eee}a{color:#4b1f6f}.no-print{margin:10px 0}@media print{.no-print{display:none}}</style></head><body><button class="no-print" onclick="print()">Salvar como PDF</button><h1>Relatório executivo de recuperação</h1><div>Período: ${fmtDate(a)||'início'} a ${fmtDate(b)||'fim'}</div><div class="summary"><div class="k">Trabalhados<b>${s.worked}</b></div><div class="k">Conectados<b>${s.connected}</b></div><div class="k">Ganhos<b>${s.won}</b></div><div class="k">Perdidos<b>${s.lost}</b></div><div class="k">Valor recuperado<b>${money(s.value)}</b></div></div><table><thead><tr><th>Clínica</th><th>Origem</th><th>Status</th><th>Resultado</th><th>Última atividade</th><th>Valor recuperado</th><th>HubSpot</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${escapeHtml(x.clinica)}</td><td>${escapeHtml(x.origem||'')}</td><td>${escapeHtml(x.etapa)}</td><td>${escapeHtml(x.resultado||'')}</td><td>${fmtDate(x.ultima_atividade)}</td><td>${Number(x.valor_recuperado)>0?money(x.valor_recuperado):''}</td><td>${x.link_crm?`<a href="${escapeAttr(x.link_crm)}">Abrir CRM</a>`:''}</td></tr>`).join('')}</tbody></table></body></html>`}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function escapeAttr(v){return escapeHtml(v)}function fmtDate(v){if(!v)return'';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v}function money(v){return Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}function parseMoney(v){return Number(String(v||'0').replace(/[^0-9,.-]/g,'').replace(/\./g,'').replace(',','.'))||0}function parseDate(v){if(!v)return null;const s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);const m=s.match(/(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:null}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');start();